### ISSUE TITLE
Can haz?

### ISSUE THREAD

**Issue by ZentaSE** [GGAlanSmithee/consuela.log#2]
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNNNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmyo++osydmdmNNNNNNNNNNNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNms/:::::::////+ymNNNNNNNNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNm+:::::::::::::::/smNNNNNNNNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNo::::::::::::::::::/hNNNNNNNMMNMMMMMMMMMMMMM
MMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNy/:::::::::::::::::::/yNNNNNMMNNMMMMMMMMMMMMM
MMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmMNdo::::::::::::::::::::::/hNNNNNNNMMMNMMMMMMMMMM
MMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNmmhs+hho/::::::::::::::::::::::::+NNNNNNMMNNNMMMMMMMMMM
MMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNmysohdddhhysoo++++++///::::::::::::://++ooooooomNNNNNNNNNNMMMMMMMMMM
MMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNs:::::/+oyyyyyyyyyyyyyhyso/::::::/syhyyssoooooomNNMMMNNNNMMMMMMMMMMM
MMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNN+:::/shys+///++oooo++//+oydy::::+dy+/:/oooo++:+NNNNNNMNNMMMMMMMMMMMM
MMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNm:::+ms/::::/ooo+oo+oo/::::/N+:::my:::/oooooos+dNNNNNNMMMMMMMMMMMMMMM
MMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNs:::hh::::::+so+////+os+::::dy///ms:/os+/////+smNNNNNNMMMMMMMMMMMMMMM
MMMMMMMNNNNNNNNNNNNNNNNNNNNNNNh/:::dy::/s/os//////+o++yo:::ymsosNs:so++++//yh+sNMMMMMMMMMMMMMMMMMMMM
MMMMMMMNNNNNNNNNNNNNNNNNMMMMNNNd+::ms:/oshd+/:--..-hy.-y/::sm:::yy+y-.     -/``+MMMMMMMMMMMMMMMMMMMM
MMMMMMMMNNNNNNNNNNNNNNNMNNdy+oyMm/:ms::://o            s/::sm::::/os`          +dNMMMMMMMMMMMMMMMMMM
MMMMMMMMMNNNNNNNNNNNNNNNd//+y::yMh/ms:::::s-          :s://hh::::::/s.        :s:/yMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNNNNNNNNNNNNNNh//+::/hNmNy:::::/o+.`    `.+o/oooyo:::::::/y/.```.:++::::yMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNNNNNNNNNNmo+oo:::+odd:::::::/o+///+++/:/y////::::::::y/+++++/:::///sMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNNNNNNNNy---y:::::/my//::::::::::////+ohmyoos///://omyssooossyyhhhdMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNNNNNNNNNysh+::::::/sdhyyyyyyyyhhhhhhdy+/:::/oooooo+/oyooooo++/::/mMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNNNNNNNNNNs::::::::://+++++/////::/y::::::::::::::::oo:::::::::sMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNNNNNNNNNN/:::::::::::::::::::::+y/::::::::::::::::/y::::::::/NMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNNNNNNNNd:::::::::::::::::::/ss::::::://:::::::/oyhy+::::::yMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNy:::::::::::::::::+s/::/osyyhhhhhyyyyyhhyydo:::::/NMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNMMNNNNNNNms::::::::::::::/y++syhdhhhhhyyyyhhhhhhhhy+::::::yMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNNNNNMMm:+s:::::::::::::oshmmddhhhhhhhhhhhhhhhhd+:::::::/mMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNMMMMMMs--/s/:::::::::::oo///+syhhyyyyyyyyyyyhho::::::::oMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNds---:s+::::::::::+y::::::/+syyyhhhhyydo/:::::::::hMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNdyo//s:----+s/:::::::::/::::::::::////////y/:::::::::+NMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMmho//::::/o+----:oo/::::::::::::::::::::::::::oo:::::::/odMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMmho/::::::::::+o:----:oo+:::::::://:::::::::::::+y/:/o+++oy+/hMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMds/::::::::::::::/+o:-----/oo++++ooo/:::/so+++++ooo/::+y::--/o:/hNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMdo/::::::::::::::::::/+o/------::::/+++//::///+++///:/+s+------y::/ysmMMMMMMMMMMMMMMMM
MMMMMMMMMMMMms/::::::::::::::::::::::/+o/:----------:/++++/::::/+ooo+h++//:--y:::y//yNMMMMMMMMMMMMMM
MMMMMMMMMMNh/:::::::::::::::::::::::::::/++/:-----------::/++o+///::+y/://+oo+:::/s+/+dMMMMMMMMMMMMM
MMMMMMMMMmo::::::::::::::::::::::::::::::://++/:------------+s+oo+/:oo::::::/:::::/+oo+hNMMMMMMMMMMM
MMMMMMMMm+::::::::::::::::::::::::::::::::::::/+o/:--------o+::::+ooo+:::::::::::::::/+ohNMMMMMMMMMM
MMMMMMMd/::::::::::::::::::::::::::::::::::::::::/+++/:---o+:::::::+h+::::::::::::::::::/+ymMMMMMMMM
MMMMMMd/:::::::::::::::::::::::::::::::::::::::::::::/+++o+:::::::::oo:::::::::::::::::::::/odNMMMMM
MMMMMm/::::::::::::::::::::::::::::::::::::::::::::::::::/::::::::::/s::oos::::::::::::::::::/omMMMM
MMMMN+:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::s/:+oo::::::::::::::::::::/yNMM
MMMMs:::::::::::::::::::::::::::::::::::::::::::::::::::::::::/::::::/s::::::::::::::::::::::::::sNM
MMMd/::::::::::::::::::::::::::::::::::::::::::::::::::////+++o+::::::+s::::::::::::::::::::::::::yM
MMMo::::::::::::::::::::::::::::::::::::::::o+++++++++++///:---o+::::::oo:::::::::::::::::::::::::/m
MMm/::::::::::::::::::::::::::::::+:::::::::y:----------------:/h/::::::o+:::::::::::::::::::::::::d
MMh::::::::::::::::::::::::::::::oo/::::::::+o----------::/++++//y:::::::s/:::::::::::::::::::::::/m
MNso/:::::::::::::::::::::::::::/y+s:::::::::so++++++++++//::::::oo::::::/y:::::::::::::::::::::::oM
MM/:+o+/::::::::::::::::::::::::sso::::::::::/y::::::::::::::::::/y:::::::+o:::++/:::::::::::::::+mM
MMh:--/+o+//:::::::::::::::::::/y:::::::::::::o+::::::::::::::::::s+:::::::y::/ys+::::::::::::::+mMM
MMMNs:---:+oso+/::::::::::::///y+:::::::::::::/y::::::::::::::::::/s:::::::oo:://::::::::::::::sNMMM
MMMMdoo/-----:/+++++++++ooooo+/s/::::::::::::::s/:::::::::::::::::/y:::::::/y:::::::::::::::/odMMMMM
MMMMh::/oo+:------------------/s:::::::::::::::oo:::::::::::::::/oo/::::::::y:::::::::::::/odMMMMMMM
MMMMh::::::+o+++++//////+++s++/::::::::::::::::/oooo++///+++oooo+/::::::::::y:::::::::+oss+:hMMMMMMM
MMMMd::::::::::::://////::/s::::::::::::::::/:::::::///////:::::::::::+/::::s/::::::::::y/::hMMMMMMM
MMMMm:::::::::::::::::::::o+::::::::::::::::+oo+::::::::::::::::::/+oo+:::::s+:::::::::yoo++/dMMMMMM
MMMMN/::::::::::::::::::::s/:::::::::::::::::::/ooooo+++++++++ooooo/::::::::s/:::::::+o/-....sMMMMMM
MMMMMo::::::::::::::::::::y:::::::::::::::::::::::::://///////::::::::::::::y:::::/++s-......+MMMMMM
MMMMMh::::::::::::::::::::hyo/:::::::::::::::::::::+/:::::::::::::::::::::/+s/////::/+o....../MMMMMM
MMMMMN/::::::::::::::::::/s-:/+++/:::::::::::::::::/+syo+/::::::::::::/+++/.```.::/-.`-o...../MMMMMM
MMMMMMy:::::::::::::::::/+y:```.-:///+++++/////+++++/-...-:///////////:-..-:::/:.``````:+....+MMMMMM
MMMMMmho/:::::::::://++++:-s:-.```````....-----...``````````````..--::::/:-..```````````/:...oMMMMMM
MMMMm++s/+++++++++//:-.....y///oo::::::::---------------:::::::::--...```````````````````o...hMMMMMM
MMMm+::s-..................s:::s.````````...............`````````````````````````````````-+..mMMMMMM
MMNo:::/s..................o/::s``````````````````````````````````````````````````````````o-:MMMMMMM
MMy:::::++................./+:/+``````````````````````````````````````````````````````````.oyMMMMMMM
Mm/::::::o/................:s:o:```````````````````````````````````````````````````````````sMMMMMMMM
My::::::::o:............-:..o+y````````````````````````````````````````````````````````````:NMMMMMMM
Mo:::::::::o/.......:///:/...+y`````````````````````````````````````````````````````````````mMMMMMMM
N/:::::::::/o........--:/:...so`````````````````````````````````````````````````````````````sMMMMMMM
m/::::::::::o/.......---.....+/`````````````````````````````````````````````````````````````/MMMMMMM
d:::::::::::++...............-+`````````````````````````````````````````````````````````````-NMMMMMM
h:::::::::::/s................s``````````````````````````````````````````````````````````````dMMMMMM
h::::::::::::+o-..............s``````````````````````````````````````````````````````````````yMMMMMM
h:::::::::::::/s.....+-.../...s``````````````````````````````````````````````````````````````oMMMMMM
h:::::::::::::++....:+...-o...s``````````````````````````````````````````````````````````````+MMMMMM
d:::::::::::::s-.../+....o-..:+``````````````````````````````````````````````````````````````/MMMMMM
d:::::::::::::s/-/o:...-s/..:o```````````````````````````````````````````````````````````````-NMMMMM
m/:::::::::::::/+/s-.-/o+o++s+```````````````````````````````````````````````````````````````-NMMMMM
N/::::::::::::::::/+++/:::::++```````````````````````````````````````````````````````````````.NMMMMM
Mo::::::::::::::::::::::::::+/```````````````````````````````````````````````````````````````.NMMMMM
My::::::::::::::::::::::::::+/```````````````````````````````````````````````````````````````.NMMMMM
Mm/:::::::::::::::::::::::::+/```````````````````````````````````````````````````````````````.NMMMMM
MMo:::::::::::::::::::::::::+/```````````````````````````````````````````````````````````````.NMMMMM
MMh:::::::::::::::::::::::::++```````````````````````````````````````````````````````````````-NMMMMM
MMN+::::::::::::::::::::::::++``````````````````````````````````````````````````````````````-yMMMMMM
MMMh::::::::::::::::::::::::++``````````````````````````````````````````````````````````./smMMMMMMMM
MMMNo:::::::::::::::::::::::++``````````````````````````````````````````````````````-/+sNMMMMMMMMMMM
MMMMm/::::::::::::::::::::::++`````````````````````````````````````````````````.:/+++/:yMMMMMMMMMMMM
MMMMMd/:::::::::::::::::::::++```````````````````````````````````````````.-:/+++/:::::oNMMMMMMMMMMMM
MMMMMMh/::::::::::::::::::::++````````````````````````````````````.-::/+++//::::::::/sNMMMMMMMMMMMMM
MMMMMMmy/:::::::::::::::::::/o/::--..````````````````...--::://++++///:::::::::::/ohNMMMMMMMMMMMMMMM
MMMMMMMNdo/::::::::::::::::::://////+++++++++++++++++++///////:::::::::::::::/+ohNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMNmhs+//:::::::::::::::::::::::::::::::::::::::::::::::::::::::/++oo+//dMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMm/+ooo+++//:::::::::::::::::::::::::::::::::::::::::/++++oo+///:::/NMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMo:::////++oooo+++++++/////:::::::::://///++++++oooo++///:::::::::yMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMd/:::::::::::////////++++++oooooooo+++so////////::::::::::::::::oNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMy::::::::::::::::::::::::::::::::::::s/:::::::::::::::::::::::+mMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNo::::::::::::::::::::::::::::::::::/s:::::::::::::::::::::::+mMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMm+::::::::::::::::::::::::::::::::/y/::::::::::::::::::::::+mMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMm/:::::::::::::::::::::::::::::::s+::::::::::::::::::::::omMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMd/::::::::::::::::::::::::::::/so:::::::::::::::::::::/yNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMd+::::::::::::::::::::::::::/yNd/:::::::::::::::::::/hMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMm+::::::::::::::::::::::::/hMMMy:::::::::::::::::::+MMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNo::::::::::::::::::::::+dMMMNy:::::::::::::::::::/hmNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNo::::::::::::::::::::/mMMMNNo/::::::::::::::::::::/oymMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMy::::::::::::::::::::/mMMNNNNdhs+//::::::::::::::::::/ohNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNh/::::::::::::::::::::+ymNNNNNNNNmdhys+////:::::::::://sNNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNNdo/::::::::::::::::::::/sdNNNNNNNNNNNNNmdhyyssooossydmNNNNNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNNNNds//:::::::::::::::::::/yNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNNNNNNNdys++////::::::::///smNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNmddhyyysssyyhdNNNNNNNNMMMNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMNNNMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

**Comment by GGAlanSmithee** [comment]
Yes...
